version: '3.4'

services:
  front-envoy:
    image: envoyproxy/envoy:v1.19-latest
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8000:8000"  # Expose Envoy on port 80
      - "8443:8443"
    depends_on:
      - publicserver
  
  publicserver:
    image: ${DOCKER_REGISTRY-}publicserver
    build:
      context: .
      dockerfile: PublicServer/Dockerfile
